# This is a basic workflow that is manually triggered

name: Pipeline Backend

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
 push:
  branches: [ main ]
 pull_request:
  branches: [ main ]
 workflow_dispatch:
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Install dependencies
    run: |
     python -m pip install --upgrade pip
     pip install pylint pytest flask
  - name: Pylint
    run: pylint `ls -R|grep .py$|xargs`
  - name: Pytest
    run: pytest `ls -R|grep test_*.py$|xargs`
